version: '3.7'

services:
  pg_db:
    container_name: pghw11_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/HW11/main
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5431:5432

volumes:
  postgres_data:
