version: '3.7'

services:
  pg_db:
    container_name: authorreg_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/reg29/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5438:5432


volumes:
  postgres_data:
